import type { BuildConfig } from "../types.ts";
import { run } from "../utils/exec.ts";

export function buildWasmBinaries(config: BuildConfig): void {
  console.log("\n--- [4/5] Cross-Compiling Clang & LLD to Wasm ---");

  run(
    `
    emcmake cmake -G Ninja -B build-wasm -S llvm
      -DCMAKE_BUILD_TYPE=MinSizeRel
      -DLLVM_ENABLE_ASSERTIONS=OFF
      -DLLVM_ENABLE_PROJECTS="clang;lld"
      -DLLVM_TARGETS_TO_BUILD="WebAssembly"
      -DLLVM_DEFAULT_TARGET_TRIPLE="wasm32-unknown-emscripten"
      -DLLVM_NATIVE_TOOL_DIR="${config.nativeBinDir}"
      -DLLVM_ENABLE_THREADS=OFF
      -DLLVM_ENABLE_BACKTRACES=OFF
      -DLLVM_ENABLE_CRASH_OVERRIDES=OFF
      -DLLVM_ENABLE_LIBXML2=OFF
      -DLLVM_ENABLE_ZLIB=OFF
      -DLLVM_ENABLE_ZSTD=OFF
      -DLLVM_ENABLE_LIBPFM=OFF
      -DLLVM_ENABLE_PIC=OFF
      -DLLVM_ENABLE_UNWIND_TABLES=OFF
      -DLLVM_INSTALL_UTILS=OFF
      -DLLVM_ENABLE_PLUGINS=OFF
      -DLLVM_ENABLE_BINDINGS=OFF
      -DLLVM_ENABLE_TELEMETRY=OFF
      -DLLVM_INCLUDE_TESTS=OFF
      -DLLVM_INCLUDE_EXAMPLES=OFF
      -DLLVM_INCLUDE_BENCHMARKS=OFF
      -DLLVM_INCLUDE_DOCS=OFF
      -DLLVM_INCLUDE_UTILS=OFF
      -DLLVM_INCLUDE_RUNTIMES=OFF
      -DLLVM_BUILD_TOOLS=OFF
      -DLLVM_BUILD_UTILS=OFF
      -DLLVM_TOOL_LLVM_LTO_BUILD=OFF
      -DLLVM_TOOL_LLVM_LTO2_BUILD=OFF
      -DCLANG_ENABLE_STATIC_ANALYZER=OFF
      -DCLANG_ENABLE_OBJC_REWRITER=OFF
      -DCLANG_ENABLE_HLSL=OFF
      -DCLANG_ENABLE_LIBXML2=OFF
      -DCLANG_PLUGIN_SUPPORT=OFF
      -DCLANG_INCLUDE_TESTS=OFF
      -DCLANG_BUILD_TOOLS=OFF
      -DCLANG_TOOL_APINOTES_TEST_BUILD=OFF
      -DCLANG_TOOL_C_INDEX_TEST_BUILD=OFF
      -DCLANG_TOOL_CIR_LSP_SERVER_BUILD=OFF
      -DCLANG_TOOL_CIR_OPT_BUILD=OFF
      -DCLANG_TOOL_CIR_TRANSLATE_BUILD=OFF
      -DCLANG_TOOL_CLANG_CHECK_BUILD=OFF
      -DCLANG_TOOL_CLANG_DIFF_BUILD=OFF
      -DCLANG_TOOL_CLANG_EXTDEF_MAPPING_BUILD=OFF
      -DCLANG_TOOL_CLANG_FORMAT_BUILD=OFF
      -DCLANG_TOOL_CLANG_FUZZER_BUILD=OFF
      -DCLANG_TOOL_CLANG_IMPORT_TEST_BUILD=OFF
      -DCLANG_TOOL_CLANG_INSTALLAPI_BUILD=OFF
      -DCLANG_TOOL_CLANG_LINKER_WRAPPER_BUILD=OFF
      -DCLANG_TOOL_CLANG_NVLINK_WRAPPER_BUILD=OFF
      -DCLANG_TOOL_CLANG_OFFLOAD_BUNDLER_BUILD=OFF
      -DCLANG_TOOL_CLANG_REFACTOR_BUILD=OFF
      -DCLANG_TOOL_CLANG_REPL_BUILD=OFF
      -DCLANG_TOOL_CLANG_SCAN_DEPS_BUILD=OFF
      -DCLANG_TOOL_CLANG_SHLIB_BUILD=OFF
      -DCLANG_TOOL_CLANG_SSAF_ANALYZER_BUILD=OFF
      -DCLANG_TOOL_CLANG_SSAF_FORMAT_BUILD=OFF
      -DCLANG_TOOL_CLANG_SSAF_LINKER_BUILD=OFF
      -DCLANG_TOOL_CLANG_SYCL_LINKER_BUILD=OFF
      -DCLANG_TOOL_DIAGTOOL_BUILD=OFF
      -DCLANG_TOOL_LIBCLANG_BUILD=OFF
      -DCLANG_TOOL_OFFLOAD_ARCH_BUILD=OFF
      -DCLANG_TOOL_SCAN_BUILD_BUILD=OFF
      -DCLANG_TOOL_SCAN_BUILD_PY_BUILD=OFF
      -DCLANG_TOOL_SCAN_VIEW_BUILD=OFF
      -DDEFAULT_SYSROOT="/sysroot"
      -DCLANG_DEFAULT_CXX_STDLIB="libc++"
      -DCLANG_DEFAULT_RTLIB="compiler-rt"
      -DCLANG_DEFAULT_LINKER="lld"
      -DCMAKE_CXX_FLAGS="${config.cxxFlags}"
      -DCMAKE_C_FLAGS="${config.cFlags}"
      -DCMAKE_EXE_LINKER_FLAGS="${config.exeLinkerFlags}"
    `,
    config.llvmDir,
    {},
    config.dryRun
  );

  run(
    `
    ninja -C build-wasm -j ${config.ninjaJobs}
      clang
      lld
    `,
    config.llvmDir,
    {},
    config.dryRun
  );
}
